import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import vm from 'node:vm';
import {__testHooks as hooks} from '../automation/chatgpt.mjs';

function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ym-completed-download-'));let clicks=0;const commands=[];const cdp={send:async(method,params)=>{commands.push({method,...params});if(params.type==='mouseReleased')clicks++},eval:async expression=>expression.includes('YM_REPAIR_DOWNLOAD_CANDIDATE')?{key:'latest-repair.zip',x:50,y:80}:expression.includes('YM_CHAT_RESPONSE_ACTIVITY')?{assistantMessages:5,assistantText:'Finished repair.zip',generating:false,href:'https://chatgpt.com/c/saved'}:false};return {dir,cdp,commands,get clicks(){return clicks},dispose(){fs.rmSync(dir,{recursive:true,force:true})}}}
test('completed repair retries past two unconfirmed clicks and accepts only a received file',async()=>{const f=fixture();try{const statuses=[];const send=f.cdp.send;f.cdp.send=async(...args)=>{await send(...args);if(f.clicks===3){const zip=path.join(f.dir,'repair.zip');fs.writeFileSync(zip,'actual downloaded bytes');fs.utimesSync(zip,new Date(0),new Date(0))}};const result=await hooks.waitRepair(f.cdp,f.dir,new Map(),s=>statuses.push(s),()=>false,0,{dataDir:f.dir,pollMs:5,downloadRetryMs:0},2000);assert.equal(path.basename(result),'repair.zip');assert.equal(f.clicks,3);assert.ok(!statuses.some(s=>/download started|finish please/.test(s)));assert.ok(f.commands.every(c=>c.method==='Input.dispatchMouseEvent'));}finally{f.dispose()}});
test('completed response exhausts six trusted download attempts and one reload without resending prompt or archive',async()=>{const f=fixture();let reloads=0;try{await assert.rejects(hooks.waitRepair(f.cdp,f.dir,new Map(),()=>{},()=>false,0,{dataDir:f.dir,pollMs:5,downloadRetryMs:0,refreshDownload:async()=>{reloads++}},2000),e=>e.code==='CHATGPT_DOWNLOAD_FAILED');assert.equal(f.clicks,6);assert.equal(reloads,1);assert.ok(f.commands.every(c=>c.method==='Input.dispatchMouseEvent'));assert.equal(JSON.parse(fs.readFileSync(path.join(f.dir,'chat-handoff/recovery.json'))).reason,'repair_download')}finally{f.dispose()}});
test('resume rejects another site or a fresh chat rather than replaying a repair request',async()=>{for(const url of ['https://evil.invalid/c/saved','https://chatgpt.com/'])await assert.rejects(hooks.resumeRepairConversation({},'',{resumeConversationUrl:url}),/saved repair conversation URL is invalid/)});
test('a changed rendered assistant count after reload cannot reset download recovery indefinitely',async()=>{const f=fixture();let reloads=0;const evaluate=f.cdp.eval;f.cdp.eval=async expression=>{const result=await evaluate(expression);return expression.includes('YM_REPAIR_DOWNLOAD_CANDIDATE')?{...result,key:reloads?'virtualized-repair.zip':result.key}:result};try{await assert.rejects(hooks.waitRepair(f.cdp,f.dir,new Map(),()=>{},()=>false,0,{dataDir:f.dir,pollMs:5,downloadRetryMs:0,refreshDownload:async()=>{reloads++}},2000),e=>e.code==='CHATGPT_DOWNLOAD_FAILED');assert.equal(f.clicks,6);assert.equal(reloads,1)}finally{f.dispose()}});
test('operator update resumes the saved handoff checkpoint once without starting another test',async()=>{const text=fs.readFileSync(new URL('../server.mjs',import.meta.url),'utf8');const body=text.slice(text.indexOf('function resumeAfterOperatorUpdate(){'),text.indexOf('function repositoryPathOrThrow(){'));const state={workflow:{repairAttempts:6,chatGPTConversationUrl:'https://chatgpt.com/c/saved'},run:{state:'failed',counts:{pass:86,fail:12}}};const callbacks=[],calls=[];const context={state,packageInfo:{version:'0.1.133'},updateResumePath:'fixture-marker',readJson:()=>({from:'0.1.132',resumeAfterUpdate:{kind:'resume-handoff'}}),fs:{rmSync(){}},activity(){},notify(){},persist(){},setTimeout:f=>callbacks.push(f),submitCurrentHandoff:async options=>calls.push(options)};vm.runInNewContext(body+';resumeAfterOperatorUpdate()',context);assert.equal(callbacks.length,1);await callbacks[0]();assert.equal(calls.length,1);assert.equal(calls[0].resume,true);assert.equal(state.workflow.repairAttempts,6);assert.equal(state.run.counts.fail,12);assert.equal(state.workflow.chatGPTConversationUrl,'https://chatgpt.com/c/saved')});
