import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {__testHooks as hooks} from '../../automation/chatgpt.mjs';
import {updateCopyFixture} from '../helpers/update-copy-fixture.mjs';
test('@updateCopy134 browser loads the verified new files when old release timestamps and sizes match',async({page})=>{const f=updateCopyFixture();try{f.copy();await page.route('http://yardmaster-update.invalid/',r=>r.fulfill({contentType:'text/html',body:fs.readFileSync(path.join(f.installed,'index.html'),'utf8')}));await page.goto('http://yardmaster-update.invalid/');await expect(page.locator('#version')).toHaveText('0.1.134');expect(JSON.parse(fs.readFileSync(path.join(f.installed,'package.json'))).version).toBe('0.1.134');f.verify()}finally{f.dispose()}});
async function withCdp(page,fn){const session=await page.context().newCDPSession(page);const cdp={send:(m,p={})=>session.send(m,p),eval:async expression=>{const r=await session.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.text);return r.result?.value}};try{return await fn(cdp)}finally{await session.detach()}}
const html=`<aside><button>Download reports.zip</button></aside><article data-testid="conversation-turn-1"><div data-message-author-role="assistant"><a download="obsolete.zip" href="data:application/zip,old">Download obsolete.zip</a></div></article><article data-testid="conversation-turn-2"><div data-message-author-role="user"><button>Download failed-source.zip</button></div></article><article data-testid="conversation-turn-3"><div data-message-author-role="assistant"><p>Finished</p><button id="repair">Download 86chaos-17.0.68-COMPLETE-APPLICATION.zip</button><pre><button>Download unrelated.zip</button></pre></div></article><form><textarea id="prompt-textarea"></textarea><button>Send</button></form><script>window.attempts=0;window.synthetic=0;document.querySelector('#repair').onclick=e=>{if(!e.isTrusted){synthetic++;return}attempts++;if(attempts<3)return;const a=document.createElement('a');a.href='data:application/zip;base64,UEsFBgAAAAAAAAAAAAAAAAAAAAAAAA==';a.download='86chaos-17.0.68-COMPLETE-APPLICATION.zip';document.body.append(a);a.click();a.remove()};</script>`;
test('@repairDownload133 completed latest response uses trusted input and recovers after two download attempts produce no file',async({page})=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ym-download-real-'));try{await page.setContent(html);await page.locator('#repair').evaluate(e=>e.click());expect(await page.evaluate(()=>synthetic)).toBe(1);const statuses=[];await withCdp(page,async cdp=>{await cdp.send('Page.setDownloadBehavior',{behavior:'allow',downloadPath:dir});const zip=await hooks.waitRepair(cdp,dir,new Map(),s=>statuses.push(s),()=>false,0,{pollMs:30,downloadRetryMs:3000},20000);expect(path.basename(zip)).toBe('86chaos-17.0.68-COMPLETE-APPLICATION.zip')});expect(await page.evaluate(()=>attempts)).toBe(3);expect(await page.locator('#prompt-textarea').inputValue()).toBe('');expect(statuses.some(s=>/finish please/.test(s))).toBe(false);}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('@repairDownload133 latest assistant scope excludes historical, user and code ZIP controls',async({page})=>{await page.setContent(html);await withCdp(page,async cdp=>expect((await hooks.repairDownloadCandidate(cdp)).label).toContain('17.0.68-COMPLETE-APPLICATION.zip'));await page.locator('#repair').evaluate(e=>e.remove());await withCdp(page,async cdp=>expect(await hooks.repairDownloadCandidate(cdp)).toBeNull());await page.setContent('<aside><button>Download unrelated.zip</button></aside><main><article><div data-message-author-role="assistant">Finished repair</div></article><button>Download current-complete.zip</button></main>');await withCdp(page,async cdp=>expect((await hooks.repairDownloadCandidate(cdp)).label).toContain('current-complete.zip'));await page.setContent('<main><p>Finished repair</p><button>Download work-complete.zip</button><pre><button>Download unrelated.zip</button></pre></main>');await withCdp(page,async cdp=>expect((await hooks.repairDownloadCandidate(cdp)).label).toContain('work-complete.zip'))});
test('@repairDownload133 resume downloads the existing response without uploading or sending another repair request',async({page})=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ym-download-resume-'));try{await page.route('https://chatgpt.com/c/saved-repair',r=>r.fulfill({contentType:'text/html',body:html.replace('if(attempts<3)return;','')}));await withCdp(page,async cdp=>{await cdp.send('Page.setDownloadBehavior',{behavior:'allow',downloadPath:dir});const result=await hooks.resumeRepairConversation(cdp,dir,{resumeConversationUrl:'https://chatgpt.com/c/saved-repair',pollMs:50,downloadRetryMs:3000});expect(result.state).toBe('downloaded')});expect(page.url()).toBe('https://chatgpt.com/c/saved-repair');expect(await page.locator('#prompt-textarea').inputValue()).toBe('');expect(await page.evaluate(()=>attempts)).toBe(1);expect(await page.locator('input[type=file]').count()).toBe(0);}finally{fs.rmSync(dir,{recursive:true,force:true})}});
