import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {__testHooks as hooks} from '../../automation/chatgpt.mjs';
import {updateCopyFixture} from '../helpers/update-copy-fixture.mjs';
import {createContinuousLoopFixture,eventually} from '../helpers/continuous-loop-fixture.mjs';
test('@updateCopy134 browser loads the verified new files when old release timestamps and sizes match',async({page})=>{const f=updateCopyFixture();try{f.copy();await page.route('http://yardmaster-update.invalid/',r=>r.fulfill({contentType:'text/html',body:fs.readFileSync(path.join(f.installed,'index.html'),'utf8')}));await page.goto('http://yardmaster-update.invalid/');await expect(page.locator('#version')).toHaveText('0.1.134');expect(JSON.parse(fs.readFileSync(path.join(f.installed,'package.json'))).version).toBe('0.1.134');f.verify()}finally{f.dispose()}});
async function withCdp(page,fn){const session=await page.context().newCDPSession(page);const cdp={send:(m,p={})=>session.send(m,p),eval:async expression=>{const r=await session.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.text);return r.result?.value}};try{return await fn(cdp)}finally{await session.detach()}}
const html=`<aside><button>Download reports.zip</button></aside><article data-testid="conversation-turn-1"><div data-message-author-role="assistant"><a download="obsolete.zip" href="data:application/zip,old">Download obsolete.zip</a></div></article><article data-testid="conversation-turn-2"><div data-message-author-role="user"><button>Download failed-source.zip</button></div></article><article data-testid="conversation-turn-3"><div data-message-author-role="assistant"><p>Finished</p><button id="repair">Download 86chaos-17.0.68-COMPLETE-APPLICATION.zip</button><pre><button>Download unrelated.zip</button></pre></div></article><form><textarea id="prompt-textarea"></textarea><button>Send</button></form><script>window.attempts=0;window.synthetic=0;document.querySelector('#repair').onclick=e=>{if(!e.isTrusted){synthetic++;return}attempts++;if(attempts<3)return;const a=document.createElement('a');a.href='data:application/zip;base64,UEsFBgAAAAAAAAAAAAAAAAAAAAAAAA==';a.download='86chaos-17.0.68-COMPLETE-APPLICATION.zip';document.body.append(a);a.click();a.remove()};</script>`;
const modernProtocol="YARDMASTER\nPOWERSHELL\n$ErrorActionPreference = 'Stop'\n$value = '$_ and $env:LOCALAPPDATA'\nWrite-Output $value\nEND_POWERSHELL\nEND";
const modernHtml=`<main><div data-turn-key="saved-turn"><div data-content-search-turn-key="fallback-turn-0"><div><h4>You said:</h4><div data-chatgpt-search-unit-key="fallback-turn-0:0:user"><button id="upload" aria-label="Yardmaster-Handoff-123.zip"></button><div data-user-message-bubble="true">Repair the attached source</div></div></div><div><div data-content-search-unit-key="fallback-turn-0:2:assistant" data-chatgpt-search-unit-key="fallback-turn-0:2:assistant"><h4 data-conversation-role="assistant">ChatGPT said:</h4><div data-markdown-copy="code-block"><button>Copy code</button><code style="white-space:pre">${modernProtocol}</code></div></div></div></div></div><form><textarea id="prompt-textarea"></textarea><button>Send</button></form></main>`;
test('@chatResponse140 a full certification blocked before execution stays full in the real operator checkpoint',async({page})=>{
 test.setTimeout(90000);const f=await createContinuousLoopFixture({initialLevel:2});try{
  fs.writeFileSync(path.join(f.repo,'gate.mjs'),"console.log('BLOCKED BEFORE TEST EXECUTION'); console.log('TOTAL: 0'); process.exitCode=1;");
  await page.goto(f.url);await f.api('/api/action',{action:'start'});
  const status=await eventually(async()=>{const s=await f.status();return s.run.state==='failed'&&s});
  expect(status.run.testType).toBe('full');expect(status.run.log.join('\n')).toContain('BLOCKED BEFORE TEST EXECUTION');expect(status.workflow.fullFirstComplete).toBe(false);
  await expect(page.locator('#runTitle')).toContainText(/Tests Failed|ChatGPT repair/,{timeout:15000});
 }finally{await f.close()}
});
test('@chatResponse140 virtualized command reply is consumed without clicking the uploaded ZIP or resending the handoff',async({page})=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ym-modern-command-'));try{await page.setContent(process.env.YARDMASTER_CHAT_DOM_FIXTURE?JSON.parse(fs.readFileSync(process.env.YARDMASTER_CHAT_DOM_FIXTURE)).main:modernHtml);await page.evaluate(()=>{window.zipClicks=0;for(const e of document.querySelectorAll('button,[role=button]'))if(/\.zip/i.test(e.getAttribute('aria-label')||e.textContent))e.addEventListener('click',()=>zipClicks++)});await withCdp(page,async cdp=>{expect(await hooks.repairDownloadCandidate(cdp,'Yardmaster-Handoff-123.zip')).toBeNull();const protocol=await hooks.assistantProtocol(cdp);expect(protocol.source).toBe('assistant-turn');expect(protocol.protocol).toContain("$ErrorActionPreference");let calls=0;const statuses=[];await expect(hooks.waitRepair(cdp,dir,new Map(),s=>statuses.push(s),()=>false,0,{artifactPath:'Yardmaster-Handoff-123.zip',pollMs:20,onAssistantProtocol:async text=>{calls++;expect(text).toBe(protocol.protocol);throw Object.assign(Error('verified command boundary'),{code:'TEST_STOP'})}},5000)).rejects.toThrow('verified command boundary');expect(calls).toBe(1);expect(statuses.some(s=>s.includes('repair is complete'))).toBe(false)});expect(await page.evaluate(()=>zipClicks)).toBe(0);if(!process.env.YARDMASTER_CHAT_DOM_FIXTURE)expect(await page.locator('#prompt-textarea').inputValue()).toBe('')}finally{fs.rmSync(dir,{recursive:true,force:true})}
});
test('@chatResponse140 virtualized latest assistant ZIP downloads while user, historical and code ZIPs remain excluded',async({page})=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ym-modern-zip-'));try{await page.setContent(`<main><div data-turn-key="old"><div data-chatgpt-search-unit-key="old:assistant"><button>old-repair.zip</button></div></div><div data-turn-key="current"><div data-chatgpt-search-unit-key="current:user"><button id="upload">source.zip</button></div><div data-chatgpt-search-unit-key="current:assistant"><h4 data-conversation-role="assistant">ChatGPT said:</h4><p>Completed repair</p><button id="repair">complete-repair.zip</button><div data-markdown-copy="code-block"><button>fake.zip</button></div></div></div><form><textarea id="prompt-textarea"></textarea></form></main><script>window.userClicks=0;document.querySelector('#upload').onclick=()=>userClicks++;document.querySelector('#repair').onclick=()=>{const a=document.createElement('a');a.href='data:application/zip;base64,UEsFBgAAAAAAAAAAAAAAAAAAAAAAAA==';a.download='complete-repair.zip';a.click()};</script>`);await withCdp(page,async cdp=>{await cdp.send('Page.setDownloadBehavior',{behavior:'allow',downloadPath:dir});expect((await hooks.repairDownloadCandidate(cdp,'source.zip')).key).toBe('complete-repair.zip');const zip=await hooks.waitRepair(cdp,dir,new Map(),()=>{},()=>false,0,{artifactPath:'source.zip',pollMs:20},5000);expect(path.basename(zip)).toBe('complete-repair.zip');await page.locator('#repair').evaluate(e=>e.remove());expect(await hooks.repairDownloadCandidate(cdp,'source.zip')).toBeNull()});expect(await page.evaluate(()=>userClicks)).toBe(0)}finally{fs.rmSync(dir,{recursive:true,force:true})}
});
test('@chatResponse140 an unscoped upload and a preview Retry button cannot establish a completed assistant repair',async({page})=>{await page.setContent('<main><button>Yardmaster-Handoff-123.zip</button><button>source.zip</button><aside><article><p>Could not load this file</p><button>Retry</button></article></aside><form><textarea></textarea></form></main>');await withCdp(page,async cdp=>{expect(await hooks.repairDownloadCandidate(cdp,'source.zip')).toBeNull();expect(await hooks.latestAssistantText(cdp)).toBe('')})});
test('@repairDownload133 completed latest response uses trusted input and recovers after two download attempts produce no file',async({page})=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ym-download-real-'));try{await page.setContent(html);await page.locator('#repair').evaluate(e=>e.click());expect(await page.evaluate(()=>synthetic)).toBe(1);const statuses=[];await withCdp(page,async cdp=>{await cdp.send('Page.setDownloadBehavior',{behavior:'allow',downloadPath:dir});const send=cdp.send;let trustedKeys=0;cdp.send=(method,params)=>{if(method==='Input.dispatchKeyEvent')trustedKeys++;return send(method,params)};const zip=await hooks.waitRepair(cdp,dir,new Map(),s=>statuses.push(s),()=>false,0,{pollMs:30,downloadRetryMs:3000},20000);expect(path.basename(zip)).toBe('86chaos-17.0.68-COMPLETE-APPLICATION.zip');expect(trustedKeys).toBeGreaterThan(0)});expect(await page.evaluate(()=>attempts)).toBe(3);expect(await page.locator('#prompt-textarea').inputValue()).toBe('');expect(statuses.some(s=>/finish please/.test(s))).toBe(false);}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('@repairDownload133 latest assistant scope excludes historical, user and code ZIP controls',async({page})=>{await page.setContent(html);await withCdp(page,async cdp=>expect((await hooks.repairDownloadCandidate(cdp)).label).toContain('17.0.68-COMPLETE-APPLICATION.zip'));await page.locator('#repair').evaluate(e=>e.remove());await withCdp(page,async cdp=>expect(await hooks.repairDownloadCandidate(cdp)).toBeNull());await page.setContent('<aside><button>Download unrelated.zip</button></aside><main><article><div data-message-author-role="assistant">Finished repair</div></article><button>Download current-complete.zip</button></main>');await withCdp(page,async cdp=>expect((await hooks.repairDownloadCandidate(cdp)).label).toContain('current-complete.zip'));await page.setContent('<main><p>Finished repair</p><button>Download work-complete.zip</button><pre><button>Download unrelated.zip</button></pre></main>');await withCdp(page,async cdp=>expect((await hooks.repairDownloadCandidate(cdp)).label).toContain('work-complete.zip'))});
test('@repairDownload133 resume downloads the existing response without uploading or sending another repair request',async({page})=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ym-download-resume-'));try{await page.route('https://chatgpt.com/c/saved-repair',r=>r.fulfill({contentType:'text/html',body:html.replace('if(attempts<3)return;','')}));await withCdp(page,async cdp=>{await cdp.send('Page.setDownloadBehavior',{behavior:'allow',downloadPath:dir});const result=await hooks.resumeRepairConversation(cdp,dir,{resumeConversationUrl:'https://chatgpt.com/c/saved-repair',pollMs:50,downloadRetryMs:3000});expect(result.state).toBe('downloaded')});expect(page.url()).toBe('https://chatgpt.com/c/saved-repair');expect(await page.locator('#prompt-textarea').inputValue()).toBe('');expect(await page.evaluate(()=>attempts)).toBe(1);expect(await page.locator('input[type=file]').count()).toBe(0);}finally{fs.rmSync(dir,{recursive:true,force:true})}});
